apply plugin: 'com.android.application'

android {
    namespace 'jp.yaegaki.omoide'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'jp.yaegaki.omoide'
        minSdk 30
        targetSdk 35
        versionCode 110
        versionName '1.1.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
